{
  "openapi": "3.0.1",
  "info": {
    "title": "Gerenciamento de Consultas",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Servidor Local"
    }
  ],
  "paths": {
    "/usuario/atualizar/{id}": {
      "put": {
        "tags": [
          "Usuário"
        ],
        "summary": "Atualiza um usuário pelo ID",
        "operationId": "atualizarUsuarioViaId",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID do usuárioo",
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "description": "Dados para atualizar o usuário",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Usuario"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Usuário atualizado com sucesso!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Usuario"
                }
              }
            }
          }
        }
      }
    },
    "/consulta/atualizar/{id}": {
      "put": {
        "tags": [
          "Consulta"
        ],
        "summary": "Atualiza uma consulta pelo ID",
        "operationId": "atualizarConsulta",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID da consulta",
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "description": "Dados para atualizar a consulta",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Consulta"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Consulta atualizada com sucesso!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Consulta"
                }
              }
            }
          }
        }
      }
    },
    "/usuario": {
      "get": {
        "tags": [
          "Usuário"
        ],
        "summary": "Lista todos os usuários",
        "operationId": "buscarTodosUsuarios",
        "responses": {
          "200": {
            "description": "Usuários listados com sucesso!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Usuario"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Usuário"
        ],
        "summary": "Cadastra um novo usuário",
        "operationId": "cadastrarUsuario",
        "requestBody": {
          "description": "Dados do novo usuário",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Usuario"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Usuário cadastrado com sucesso!",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Usuario"
                }
              }
            }
          }
        }
      }
    },
    "/consulta": {
      "get": {
        "tags": [
          "Consulta"
        ],
        "summary": "Lista todas as consultas",
        "operationId": "listarConsultas",
        "responses": {
          "200": {
            "description": "Consultas listadas",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Consulta"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Consulta"
        ],
        "summary": "Cadastra uma nova consulta",
        "operationId": "cadastrarConsulta",
        "requestBody": {
          "description": "Dados da nova consulta",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Consulta"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Consulta cadastrada",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Consulta"
                }
              }
            }
          }
        }
      }
    },
    "/usuario/{id}": {
      "get": {
        "tags": [
          "Usuário"
        ],
        "summary": "Busca um usuário pelo ID",
        "operationId": "buscarUsuarioPorId",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID do usuário",
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Usuario"
                }
              }
            }
          }
        }
      }
    },
    "/consulta/{id}": {
      "get": {
        "tags": [
          "Consulta"
        ],
        "summary": "Busca uma consulta pelo ID",
        "operationId": "buscarConsultaPorId",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID da consulta",
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Consulta encontrada",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Consulta"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Consulta"
        ],
        "summary": "Deleta uma consulta pelo ID",
        "operationId": "deletarConsulta",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID da consulta",
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Consulta deletada"
          }
        }
      }
    },
    "/usuario/delete/{id}": {
      "delete": {
        "tags": [
          "Usuário"
        ],
        "summary": "Deleta um usuário pelo ID",
        "operationId": "deletarUsuarioPorId",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID do usuário",
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário deletado"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Usuario": {
        "type": "object",
        "properties": {
          "idUsuario": {
            "type": "integer",
            "format": "int64"
          },
          "nomeUsuario": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "cpf": {
            "type": "string"
          },
          "telefone": {
            "type": "string"
          },
          "dataNascimento": {
            "type": "string",
            "format": "date-time"
          },
          "permissao": {
            "type": "string",
            "enum": [
              "ADMIN",
              "SECRETARIO"
            ]
          }
        }
      },
      "Consulta": {
        "type": "object",
        "properties": {
          "idConsulta": {
            "type": "integer",
            "format": "int64"
          },
          "dataConsulta": {
            "type": "string",
            "format": "date-time"
          },
          "profissional": {
            "type": "string"
          },
          "especialidade": {
            "type": "string"
          },
          "usuario": {
            "$ref": "#/components/schemas/Usuario"
          }
        }
      }
    }
  }
}
