{
  "openapi": "3.0.1",
  "info": {
    "title": "Gerenciamento de Consultas",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/usuario/atualizar/{id}": {
      "put": {
        "tags": [
          "usuario-controller"
        ],
        "operationId": "atualizarUsuarioViaId",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Usuario"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Usuario"
                }
              }
            }
          }
        }
      }
    },
    "/consulta/atualizar/{id}": {
      "put": {
        "tags": [
          "consulta-controller"
        ],
        "operationId": "atualizarConsulta",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Consulta"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Consulta"
                }
              }
            }
          }
        }
      }
    },
    "/usuario": {
      "get": {
        "tags": [
          "usuario-controller"
        ],
        "operationId": "buscarTodosUsuarios",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Usuario"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "usuario-controller"
        ],
        "operationId": "cadastrarUsuario",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Usuario"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Usuario"
                }
              }
            }
          }
        }
      }
    },
    "/consulta": {
      "get": {
        "tags": [
          "consulta-controller"
        ],
        "operationId": "listarUsuarios",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Consulta"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "consulta-controller"
        ],
        "operationId": "cadastrarConsulta",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Consulta"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Consulta"
                }
              }
            }
          }
        }
      }
    },
    "/usuario/{id}": {
      "get": {
        "tags": [
          "usuario-controller"
        ],
        "operationId": "buscarUsuarioPorId",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Usuario"
                }
              }
            }
          }
        }
      }
    },
    "/consulta/{id}": {
      "get": {
        "tags": [
          "consulta-controller"
        ],
        "operationId": "buscarConsulta",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Consulta"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "consulta-controller"
        ],
        "operationId": "deletarConsulta",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/usuario/delete/{id}": {
      "delete": {
        "tags": [
          "usuario-controller"
        ],
        "operationId": "deletarUsuarioPorId",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Usuario": {
        "type": "object",
        "properties": {
          "idUsuario": {
            "type": "integer",
            "format": "int64"
          },
          "nomeUsuario": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "cpf": {
            "type": "string"
          },
          "telefone": {
            "type": "string"
          },
          "dataNascimento": {
            "type": "string",
            "format": "date-time"
          },
          "permissao": {
            "type": "string",
            "enum": [
              "ADMIN",
              "SECRETARIO"
            ]
          }
        }
      },
      "Consulta": {
        "type": "object",
        "properties": {
          "idConsulta": {
            "type": "integer",
            "format": "int64"
          },
          "dataConsulta": {
            "type": "string",
            "format": "date-time"
          },
          "profissional": {
            "type": "string"
          },
          "especialidade": {
            "type": "string"
          },
          "usuario": {
            "$ref": "#/components/schemas/Usuario"
          }
        }
      }
    }
  }
}